

<?php
	$data_iden	= $this->db->get('identitas')->result_array();
	
	echo "<table class='gridtable2' border='0' width='100%' cellpadding='2'>";
		echo "<tr>";
			echo "<td class='header_style_company' width='65%'>".$data_iden[0]['nama_resmi']."</td>";
			echo "<td class='header_style_company bold color_req' colspan='2' style='text-align: right;'>INVOICE ".$header[0]->no_invoice."</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td class='header_style_alamat'>".strtoupper($data_iden[0]['alamat_baris1'])."</td>";
			echo "<td class='header_style_alamat' width='18%'></td>";
			echo "<td class='header_style_alamat'></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td class='header_style_alamat'>".strtoupper($data_iden[0]['alamat_baris2'])."</td>";
			echo "<td class='header_style_alamat'></td>";
			echo "<td class='header_style_alamat'></td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td class='header_style_alamat'>".strtoupper($data_iden[0]['alamat_baris3'])."</td>";
			echo "<td class='header_style_alamat'></td>";
			echo "<td class='header_style_alamat'></td>";
		echo "</tr>";
	echo "</table>";
	echo "<br>";
	echo "<table border='0' width='100%' cellpadding='0'>";
		echo "<tr>";
			echo "<td width='44%' style='vertical-align:top;'>";
				echo "<table class='default' border='0' width='100%' cellpadding='2'>";
					echo "<tr>";
						echo "<td class='header_style2 bold'>BUYER</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>".strtoupper(get_name('customer','nm_customer','id_customer',$header[0]->id_customer))."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>".strtoupper(get_name('customer','alamat','id_customer',$header[0]->id_customer))."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>PHONE ".strtoupper(get_name('customer','telpon','id_customer',$header[0]->id_customer))."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>EMAIL ".strtoupper(get_name('customer','email','id_customer',$header[0]->id_customer))."</td>";
					echo "</tr>";
				echo "</table>";
			echo "</td>";
			echo "<td width='6%'></td>";
			echo "<td width='44%' style='vertical-align:top;'>";
				echo "<table class='default' width='100%' cellpadding='2'>";
					echo "<tr>";
						echo "<td class='header_style2 bold' colspan='3'>INFORMATION</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td width='30%'>PO NO.</td>";
						echo "<td width='5%'>:</td>";
						echo "<td>".$header[0]->no_po."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>INVOICE NO.</td>";
						echo "<td>:</td>";
						echo "<td>".$header[0]->no_faktur."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>TAX INVOICE NO.</td>";
						echo "<td>:</td>";
						echo "<td>".$header[0]->no_pajak."</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>PAYMENT TERM</td>";
						echo "<td>:</td>";
						echo "<td>".$header[0]->payment_term." Days</td>";
					echo "</tr>";
					echo "<tr>";
						echo "<td>TYPE OF BILL</td>";
						echo "<td>:</td>";
						echo "<td>".$jenis_invoice."</td>";
					echo "</tr>";
				echo "</table>";
			echo "</td>";
		echo "</tr>";
	echo "</table>";
	echo "<br>";
?>